# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GLj0Bktr6YxS6uqiWdc6TtHhC9I5sPlY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("placement.csv")
df.head()

df.info()

df.shape

df= df.iloc[ : ,1:]

df.head()

plt.scatter(df["cgpa"],df["iq"])

plt.scatter(df["cgpa"],df["iq"],c=df["placement"])
plt.show()

X=df.iloc[ : ,0:1]
X.head()

Y=df.iloc[ : ,-1]
Y.head()

df.shape

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.1)

X_train

X_test

Y_train

Y_test

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_train

X_test = scaler.fit_transform(X_test)
X_test

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train,Y_train)

Y_pred = clf.predict(X_test)
Y_pred

Y_test

from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

Y_train.shape

Y_train

X_train

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(X_train,Y_train.values,clf=clf, legend=2)

